name: multisc-viewer

services:
  data:
    build: ./data
    volumes:
      - data:/data
  multisc-daemon:
    build: ./multisc-daemon
    volumes:
      - data:/data
    depends_on:
      - data
  multisc-viewer:
    build: ./multisc-viewer
    ports:
      - "4173:443"
    volumes:
      - data:/data:ro
    depends_on:
      - data
volumes:
  data:
    driver: local
